/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grupo1.leasing.presentacion;

import com.grupo1.leasing.calculos.Formulas;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hiros
 */
public class FrmOperativo extends javax.swing.JFrame {
    
    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    /**
     * Creates new form FrmOperativo
     */
    public FrmOperativo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtInteres = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtResidual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtN = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cboMoneda = new javax.swing.JComboBox<>();
        lblCuota = new javax.swing.JLabel();
        lblEscudoAnual = new javax.swing.JLabel();
        lblValorPresente = new javax.swing.JLabel();
        lblAhorroFinal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCuota = new javax.swing.JTextField();
        lblMonedaCuota = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbCompra = new javax.swing.JRadioButton();
        rbCuota = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leasing");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tasas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N

        jLabel1.setText("Interés: ");

        jLabel2.setText("Descuento: ");

        jLabel3.setText("Valor Residual:");

        jLabel5.setText("%");

        jLabel6.setText("%");

        jLabel7.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtResidual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(txtResidual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 195, 600, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Leasing");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 21, 202, -1));

        jLabel8.setText("Valor del Bien: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 104, -1, -1));
        getContentPane().add(txtBien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 98, 100, -1));

        jLabel9.setText("Número de Periodos: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 102, -1, -1));
        getContentPane().add(txtN, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 98, 56, -1));

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 147, 76));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(this.modelo);
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 815, 218));

        cboMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soles", "Dólares", "Euros" }));
        getContentPane().add(cboMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 98, 120, -1));

        lblCuota.setText("-");
        getContentPane().add(lblCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 527, -1, -1));

        lblEscudoAnual.setText("-");
        getContentPane().add(lblEscudoAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 566, -1, -1));

        lblValorPresente.setText("jLabel10");
        getContentPane().add(lblValorPresente, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 605, -1, -1));

        lblAhorroFinal.setText("jLabel10");
        getContentPane().add(lblAhorroFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 644, -1, -1));

        jLabel10.setText("Valor Cuota");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 154, -1, -1));

        txtCuota.setEditable(false);
        getContentPane().add(txtCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 100, -1));

        lblMonedaCuota.setText("-");
        getContentPane().add(lblMonedaCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 154, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Modalidad\n"));

        buttonGroup1.add(rbCompra);
        rbCompra.setSelected(true);
        rbCompra.setText("Con Opcion de Compra");
        rbCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCompraActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCuota);
        rbCuota.setText("Con Cuota");
        rbCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCuotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCompra)
                    .addComponent(rbCuota))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(rbCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCuota)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 230, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double bien = Double.parseDouble(txtBien.getText());
        double cuota;
        if(txtCuota.getText().isEmpty())
            cuota= 0.0d;
        else{
            cuota = Double.parseDouble(txtCuota.getText());
        }
        int n = Integer.parseInt(txtN.getText());
        double tInteres = Double.parseDouble(txtInteres.getText())/100;
        double tDescuento = Double.parseDouble(txtDescuento.getText())/100;
        double tResidual = Double.parseDouble(txtResidual.getText())/100;
        boolean opcionCompra = rbCompra.isSelected();
        Formulas formula = new Formulas(tInteres, bien, cuota, n, tResidual, tDescuento, opcionCompra);
        //Financiero -> con opcion de compra
        if(rbCompra.isSelected()){
            this.mostrarFinanciero(formula);
        }else{
            this.mostrarOperativo(formula);
            
        }
            
        
        
        lblCuota.setText("Cuota: "+String.format(Locale.UK, "%,.2f",formula.getCuota())+" "+cboMoneda.getSelectedItem().toString());
        if(!opcionCompra){
            lblEscudoAnual.setText("Escudo Fiscal Anual: "+String.format(Locale.UK, "%,.2f",formula.getEscudoFiscalXAño())+" "+cboMoneda.getSelectedItem().toString());
        }else{
            lblEscudoAnual.setText("");
        }
        lblValorPresente.setText("Valor Presente: "+String.format(Locale.UK, "%,.2f", formula.getValorPresente())+" "+cboMoneda.getSelectedItem().toString());
        lblAhorroFinal.setText("Ahorro por Leasing: "+String.format(Locale.UK, "%,.2f", formula.getAhorroFinal())+" "+cboMoneda.getSelectedItem().toString());
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void rbCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCompraActionPerformed
        if(rbCompra.isSelected()){
            txtCuota.setText("");
            txtCuota.setEditable(false);
            txtInteres.setEditable(true);
        }
    }//GEN-LAST:event_rbCompraActionPerformed

    private void rbCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCuotaActionPerformed
       if(rbCuota.isSelected()){
           txtInteres.setText("");
           txtInteres.setEditable(false);
           txtCuota.setEditable(true);
       }
    }//GEN-LAST:event_rbCuotaActionPerformed
    
    
    private void mostrarFinanciero(Formulas f){
        Object datos[][] = new Object[f.getN()+1][5];
        String titulos[] = {"PERIODO","CUOTA","INTERES","AMORTIZACION","SALDO"};
        datos[0][0] = "0";
        datos[0][1] = "";
        datos[0][2] = "";
        datos[0][3] = "";
        datos[0][4] = String.format(Locale.UK, "%,.2f", f.getValorBien());
        for(int i=1;i<=f.getN();i++){
            double fila[] = f.getTablaInteres_Amort_Saldo()[i-1];
            datos[i][0] = i;
            datos[i][1] = String.format(Locale.UK, "%,.2f", f.getCuota());
            datos[i][2] = String.format(Locale.UK, "%,.2f", fila[0]);
            datos[i][3] = String.format(Locale.UK, "%,.2f", fila[1]);
            datos[i][4] = String.format(Locale.UK, "%,.2f", fila[2]);
        }
        modelo.setDataVector(datos, titulos);
    }
    
    private void mostrarOperativo(Formulas f){
        Object datos[][] = new Object[f.getN()+1][4];
        String titulos[] = {"PERIODO","CUOTA","INTERES","AMORTIZACION"};
        datos[0][0] = "0";
        datos[0][1] = "";
        datos[0][2] = "";
        datos[0][3] = "";
        for(int i=1;i<=f.getN();i++){
            double fila[] = f.getTablaInteres_Amort_Saldo()[i-1];
            datos[i][0] = i;
            datos[i][1] = String.format(Locale.UK, "%,.2f", f.getCuota());
            datos[i][2] = String.format(Locale.UK, "%,.2f", fila[0]);
            datos[i][3] = String.format(Locale.UK, "%,.2f", fila[1]);
        }
        modelo.setDataVector(datos, titulos);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOperativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboMoneda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAhorroFinal;
    private javax.swing.JLabel lblCuota;
    private javax.swing.JLabel lblEscudoAnual;
    private javax.swing.JLabel lblMonedaCuota;
    private javax.swing.JLabel lblValorPresente;
    private javax.swing.JRadioButton rbCompra;
    private javax.swing.JRadioButton rbCuota;
    private javax.swing.JTextField txtBien;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtResidual;
    // End of variables declaration//GEN-END:variables
}
